# Generated by Django 4.2.7 on 2023-11-27 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, verbose_name='Nazwa kategorii')),
            ],
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('origin_city', models.CharField(max_length=64)),
                ('origin_airport', models.CharField(max_length=64)),
                ('destination_city', models.CharField(max_length=64)),
                ('destination_airport', models.CharField(max_length=64)),
                ('out_date', models.DateField()),
                ('return_date', models.DateField()),
                ('stop_overs', models.PositiveSmallIntegerField()),
                ('via_city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FlightDataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.category')),
                ('flight_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.flightdata')),
            ],
        ),
        migrations.AddField(
            model_name='flightdata',
            name='categories',
            field=models.ManyToManyField(through='search_app.FlightDataCategory', to='search_app.category'),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
