# Generated by Django 4.2.7 on 2023-12-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_rename_destination_airport_flightdata_destination_airport_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightdata',
            old_name='user_id',
            new_name='user',
        ),
    ]
