# Generated by Django 4.2.7 on 2023-12-04 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search_app', '0003_rename_user_id_flightdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
